
----SQL SERVER

select * from EMPLOYEE

select empcode,empfname,   -----SELECT WHICH COLUMNS YOU WANT
case empcode -----------------------SELECT WHICH COLUMNS YOU WANTS SOME CHANGES
when 9499 then 'aditya'-----------------WHERE EMPCODE 9499 PUT THERE  'ADITYA
when 9900 then 'rohit'--------------------- WHERE EMPCODE 9900 PUT THERE ROHIT
end as emp---------------------------------------END AND GIVE NAME TO ALIAS TO CHANGES COLUMN
from EMPLOYEE-------------------------------------------FROM MAIN TABLE


SELECT * FROM EMPLOYEE

---UPDATE SALARY WHERE 3100 THERE 25000 AND 5000 THERE 25700
SELECT EMPCODE,EMPFNAME,EMPLNAME,SALARY,
CASE SALARY
WHEN 3100 THEN 25000
WHEN 5000 THEN 25700
WHEN 2940 THEN 28000
END AS UPDATED_SALARY
FROM EMPLOYEE

----UPDATE COMMISSION 0 THERE 500 AND WHERE 1400 THERE 2500

SELECT EMPFNAME,EMPLNAME,COMMISSION,
CASE COMMISSION 
WHEN 0 THEN 500
WHEN 1400 THEN 2500
END AS NEW_COMMISSION 
FROM EMPLOYEE

------WITH ALL COLUMNS
SELECT * ,
CASE EMPCODE 
WHEN 9782 THEN 0
WHEN 9591 THEN 12
WHEN 9777 THEN 15
END AS NEW_ECODE
FROM EMPLOYEE

SELECT * ,
CASE EMPCODE 
WHEN 9369 THEN 0  
END AS NEW_COLUMN
FROM EMPLOYEE