---LIKE OPERATORS
SELECT * FROM ACTOR

----FOR FINDING NAME START WITH LETTER A

SELECT * FROM ACTOR WHERE FIRST_NAME ILIKE 'A%'



----FOR FINDING NAME END WITH LETTER A

SELECT * FROM ACTOR WHERE FIRST_NAME ILIKE '%A'

---FOR FINDING NAME 

SELECT * FROM ACTOR WHERE FIRST_NAME ILIKE '%JULIA%'


---FOR FINDING NAME CHARACTER CONTAIN A ON 3RD POSITION 

SELECT * FROM ACTOR WHERE FIRST_NAME ILIKE '__A'


---FOR FINDING NAME CHARACTER IN MID POSITION

SELECT * FROM ACTOR WHERE FIRST_NAME ILIKE '__A__'

